# Big Data - Aula 4 
---

# Aula Prática: Python for DataScientists - Pandas + Sklearn

# Algoritmic Concepts Revision and Distributed Computing Challenges

---

# Pandas + SkLearn

A Melhor forma é usar a linguagem para resolver um problema real. 
Vamos carregar dados de um *dataset* de preços de casas na califórnia para determinarmos: 

- Quantas casas existem abaixo de 200 000 Dollars 
- Quais os 2 locais onde as casas são mais baratas 

- Quais os melhores negócios (casas sub valorizadas) - Classificação/Regressão
- Quanto valeria uma casa na zona x, para 4 pessoas e com 200 $m^2$ ?  - Regressão


(Do conjunto de perguntas em cima, quais são perguntas de DataMining e quais são perguntas exploratórias (queries))

<font color='forestgreen'>
O dataset que vamos descarregar é do SkLearn, manipula-lo de forma a obter algumas análises exploratórias dos dados (pre-datamining). 



## DataSet de Casas

In [ ]:
# Start by importing the modules

from sklearn import datasets
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
#import data to variable

data = datasets.california_housing.fetch_california_housing()
#show disorganized data
data

In [ ]:
#first, let's print a description
print(data.DESCR)

#what is this object type?
print(type(data.DESCR))

O que podemos concluir da descrição das features?

Que são médias locais.

In [ ]:
# Qual a classe dos componentes de data?

print(type(data.target))
print(type(data.data))

data.feature_names

In [ ]:
dframe = pd.DataFrame(data=data.data, columns=data.feature_names)
dframe.head()


ou seja, obtemos algo semelhante a um "excel"

In [ ]:
# Quão esparsos são estes dados:

plt.figure()
plt.title("espalhamento geográfico dos dados")
plt.xlabel("Latitude")
plt.ylabel("Longitude")
plt.grid()
plt.axis('equal')
plt.plot(dframe.Longitude, dframe.Latitude,  '.', color="b")
plt.show()

<img src="./images/calif.png" style="width:60%; margin-left:0px"/>


### Mas faltam os dados dos preços...

In [ ]:
print(data.DESCR)

In [ ]:
#ah! está no "target":
print(data.target)

data.target.shape

In [ ]:
print(data.data.shape)
print(data.target.shape)
print(data.target.reshape(-1,1).shape)

In [ ]:
#porque o s valores estão em centenas de milhares de dollars, multiplicamos por 100 000

new_data =np.concatenate((data.data, data.target.reshape(-1,1)*100000), axis=1)

print(data.data.shape, new_data.shape)

print(type(data.feature_names))
#para adicionar um valor a uma lista podmeos usar .append ou <list> + []. Vamos usar a segunda:

names = data.feature_names + ["preços"]
print(names)

In [ ]:
dframe = pd.DataFrame(new_data, columns=names)

dframe.head()


# Exercícios usando a DataFrame

Relembrando as perguntas de hoje:
    
- Quantas casas existem abaixo de 200 000 Dollars
- Quais os 2 locais onde as casas são mais baratas



### Quantas casas existem abaixo de 200 000 Dollars ?

(Recordam-se do problema das 10 palavras mais usadas numa lista da Aula Passada? Como resolveriam com Pandas?)

In [ ]:
dframe["preços"]
#dframe.loc[dframe["preços"]<200000,"preços"]

#dframe.iloc[0:10,]


a= [1,2,3]
b = [4,5,6]
[(i,j) for i,j in zip(a,b)]

#X = [a and b and c for a,b,c in zip(list(dframe["preços"]<200000), list(dframe["preços"]>200), list(dframe["Population"]>200))]
#X

#small_price_data = dframe.loc[,:]
#small_price_data.head()

In [ ]:
small_price_data.mean()

### Quais os 2 locais onde as casas são mais baratas?

In [ ]:

dframe.sort_values("preços").iloc[0:2,:]

### Já agora, qual a média do preço das casas:

In [ ]:
#dframe.agg(["mean"])["preços"]

#dframe.groupby(by=["HouseAge", "MedInc"]).mean().head()

X = dframe.groupby(by=["HouseAge", "MedInc"])
?X.filter()

#dframe[(dframe["preços"]<200000) & (dframe["Population"]>20000)] 


# Mais informação para melhorar a aula da hoje (e fazer os TPCs):
    
- pandas: https://pandas.pydata.org/pandas-docs/stable/10min.html
- sklearn: http://scikit-learn.org/stable/tutorial/index.html

# Algoritmic Concepts Revision and Distributed Computing Challenges

## PARTE 2
---


# 4) Graph Based Data - Inverted Indexing
----

An inverted index is a data structure that makes it easy, given a term, to find (pointers to) all the places where that term occurs.


<img src="images/inv_index.png" style="width:70%" />


### Vamos implementar um inverted index?

Considerem o seguinte texto, dividido por pontos finais:

In [1]:
raw = "In statistics, maximum likelihood estimation(MLE) is a method of estimating the parameters of a statistical model given observations, by finding the parameter values that maximize the likelihood of making the observations given the parameters. MLE can be seen as a special case of the maximum a posteriori estimation(MAP) that assumes a uniform prior distribution of the parameters, or as a variant of the MAP that ignores the prior and which therefore is unregularized. The method of maximum likelihood corresponds to many well-known estimation methods in statistics. For example, one may be interested in the heights of adult female penguins, but is unable to measure the height of every single penguin in a population due to cost or time constraints. Assuming that the heights are normally distributed with some unknown mean and variance, the mean and variance can be estimated with MLE while only knowing the heights of some sample of the overall population. MLE would accomplish this by taking the mean and variance as parameters and finding particular parametric values that make the observed results the most probable given the model. In general, for a fixed set of data and underlying statistical model, the method of maximum likelihood selects the set of values of the model parameters that maximizes the likelihood function. Intuitively, this maximizes the 'agreement' of the selected model with the observed data, and for discrete random variables it indeed maximizes the probability of the observed data under the resulting distribution. Maximum likelihood estimation gives a unified approach to estimation, which is well-defined in the case of the normal distribution and many other problems."

raw_list = raw.split(".")
len(raw_list)

10

In [ ]:
"{}.".format(raw_list[0])

In [ ]:
"{}.".format(raw_list[1])

In [ ]:
i_index = {}
i_index["in"] = {0:1} #word in, appears in doc 0, 1 time
i_index["likelihood"] = {1:1} #word in, appears in doc 1, 1 time

print(i_index)

## Trabalho de Casa 1

1) Implement in python a function i_index_gen() that given as input a set of documents (an array of strings) returns an  inverted index based. Clean the text from punctuations chars or upper letters. 

2) Make a second function that returns the same i_index based on a pandas DataFrame without indexes

3) Make a third function that returns the same i_index based on a pandas DataFrame using indexes

4) Compare the performance for the three methods using ```%%time``` (you should increase your text example) and take your conclusions how lists, DataFrames (with or without indexes) manage searches


**Don't forget to**
- present all results in a python notebook;
- Comment your code;

Good Luck

In [ ]:
# Example on the usage of %timeit
import math
%timeit [math.cos((i/2**i)**3) for i in range(1,10000)]
print("----")
%timeit [(i)**3 for i in range(1,10000)]

In [ ]:
%%time
print("ola")

---

#### Problems in Big Data Scenario?

---

- Inverted indexing is fundamentally a very large search problem.
- Again, problems arise when data does not fit in memory or a single CPU is too short.
- How to deal with millions of files or a giant ```i_index```? 

# 5) Matrix Multiplication

Matrix multiplication is used for almost any machine learning model creation since most methods are nowadays stronlgy supported by linear algebra.

For instance: 

- Distance measure;
- Gradient Calculation;
- Graph Calculation;

Let's look an example in distance measure between x points.

In [ ]:
import numpy as np
A = np.round(np.random.random([4,4])*100)
A = np.tril(A)

print(A)
b = np.ones([4,1])*2
print(b)

np.matmul(A,b)

---

#### Problems in Big Data Scenario?

---

- If Initial Matrix too large for memory? Apply a row multiplication per node!?

- If not even a single line is able to be fitted in memory? Notice that each input in the resulting vector depends entirely on a single line of the matrix

<img src="./images/matmul.png"/>

## How do this applies to distance calculation?

How to calculate the distance between this two points (a,b) in $R^N$?


$$D(\vec{a},\vec{b}) = \sqrt{(a_x^2 - b_x^2) + (a_y^2 - b_y^2) + ...} = \sqrt{\sum_i^N{\Delta ab_i ^2}} $$

This is the so called Norm2 distance. There are others like Norm1 (Manhathan distance) where $D(a,b) = \sum_i^{N}{|\Delta ab_i|}$

Consider a matrix 


$$W =  \begin{bmatrix}
    2 & -1 \\
    5 & 1 \\
    6 & 9 \\
    -2 & 3    
\end{bmatrix} = \begin{bmatrix}
    a \\
    b \\
    c \\
    d \\    
\end{bmatrix}$$

Let's compute the norm2 between each pair of points using normal programming techniques:

In [194]:
import numpy as np, math
W = [[2, 1], [5,1], [6,9], [-2,3]]
W = np.array(W)
W

array([[ 2,  1],
       [ 5,  1],
       [ 6,  9],
       [-2,  3]])

In [196]:
NW = []
for w1 in W:
    NW.append([])
    for w2 in W:
        NW[-1].append(0)
        for d in range(len(W[0])):
            NW[-1][-1] += (w1[d]-w2[d])**2
        NW[-1][-1] = math.sqrt(NW[-1][-1])
        
M = np.array(NW)

In [197]:
print(M)
print("----------------")
print(M-M.T)

[[  0.           3.           8.94427191   4.47213595]
 [  3.           0.           8.06225775   7.28010989]
 [  8.94427191   8.06225775   0.          10.        ]
 [  4.47213595   7.28010989  10.           0.        ]]
----------------
[[ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]


In [208]:
M = np.zeros((W.shape[0],W.shape[0]))

for d in range(W.shape[1]):
    w = np.repeat(W[:,d].reshape(-1,1),W.shape[0], axis=1)
    M += (w-w.T)**2
np.sqrt(M)

array([[  0.        ,   3.        ,   8.94427191,   4.47213595],
       [  3.        ,   0.        ,   8.06225775,   7.28010989],
       [  8.94427191,   8.06225775,   0.        ,  10.        ],
       [  4.47213595,   7.28010989,  10.        ,   0.        ]])

In [214]:
W = np.random.random([10000,2])
W

array([[ 0.69168128,  0.95795148],
       [ 0.69728775,  0.58615352],
       [ 0.03548373,  0.96888841],
       ..., 
       [ 0.27724978,  0.92632415],
       [ 0.23730736,  0.81649573],
       [ 0.57104187,  0.10000069]])

In [212]:
%%time
NW = []
for w1 in W:
    NW.append([])
    for w2 in W:
        NW[-1].append(0)
        for d in range(len(W[0])):
            NW[-1][-1] += (w1[d]-w2[d])**2
        NW[-1][-1] = math.sqrt(NW[-1][-1])
        
M = np.array(NW)
print(M)

[[ 0.          0.58875073  0.78891475 ...,  0.17017593  0.0838973
   0.89904977]
 [ 0.58875073  0.          0.65226429 ...,  0.50255283  0.50536241
   0.74941776]
 [ 0.78891475  0.65226429  0.         ...,  0.61887957  0.73582055
   0.11302332]
 ..., 
 [ 0.17017593  0.50255283  0.61887957 ...,  0.          0.12752133
   0.72933304]
 [ 0.0838973   0.50536241  0.73582055 ...,  0.12752133  0.          0.84764047]
 [ 0.89904977  0.74941776  0.11302332 ...,  0.72933304  0.84764047  0.        ]]
CPU times: user 2.92 s, sys: 9.23 ms, total: 2.93 s
Wall time: 2.93 s


In [215]:
%%time
m = np.zeros((W.shape[0],W.shape[0]))

for d in range(W.shape[1]):
    w = np.repeat(W[:,d].reshape(-1,1),W.shape[0], axis=1)
    m += (w-w.T)**2
    
M = np.sqrt(m)
print(M)

[[ 0.          0.37184023  0.65628869 ...,  0.41563657  0.47588379
   0.86639103]
 [ 0.37184023  0.          0.76450674 ...,  0.54050713  0.51443123
   0.5022774 ]
 [ 0.65628869  0.76450674  0.         ...,  0.2454843   0.25289584
   1.02068035]
 ..., 
 [ 0.41563657  0.54050713  0.2454843  ...,  0.          0.11686607
   0.87699729]
 [ 0.47588379  0.51443123  0.25289584 ...,  0.11686607  0.          0.7904074 ]
 [ 0.86639103  0.5022774   1.02068035 ...,  0.87699729  0.7904074   0.        ]]
CPU times: user 5.95 s, sys: 2.44 s, total: 8.38 s
Wall time: 8.67 s


In [ ]:
%%time
#W = np.random.random([1000,2])
w = (np.repeat(W.reshape(-1,1,W.shape[1]),W.shape[0], axis=1)-np.repeat(W.reshape(1,-1,W.shape[1]),W.shape[0], axis=0))**2
M = np.sum(w, axis=2)
print(M)

E este método como funciona?

# Data Streamming (realtime data)

This is a common situation in BigData that is not comparable with a normal data Scenario:

**Data Streaming appears when we can think of the data as infinite and non-stationary (the distribution changes over time)**

e.g. Google queries, Twitter or Facebook status updates

### Characteristics:

- The system cannot store the entire stream
- Streams often deliver elements very rapidly. 
- We must process elements in real time, or we lose the opportunity to process them at all (forced to be main memory calculations)
- ** Approximate solutions are often acceptable**



### Kind of problems 

- Queries over sliding windows
- Filtering a data stream
- Select elements with property x from the stream
- Counting distinct elements
- Number of distinct elements in the last k elements of the stream
- Estimating moments (average, Standard Deviation, etc.)
- Finding frequent elements
...



## Let's see 2 Examples

### 1) Fixed Size Random Sampling (with substitution of new values over old values)

Imagine you have a list of user queries with the following fields: 

Queries(UserID, QueryID, TimeStamp)

Consider the following question: ***in the set of user queries, how many queries were used twice by the same user***? 

and consider you cannot keep all data: you have to random sampling your data.

(hash functions are used for speed!)



Consider we have a d = 1000 (doubled queries) and x = 5000 (unique queries). So, a total of 7000 queries and 6000 unique queries (d+x).

The right answer would be $1000/6000 = 16\%$ (1000 queries of 6000 unique queries)

Let us now random sample and see the results:

In [219]:
#generating data
import math, random
queries = np.random.choice(range(200000), 6000, replace=False)

#create queryID, userID, TimeStamp
queries = np.concatenate([queries, np.random.choice(queries,1000, replace=False)]).reshape(-1,1)
np.random.shuffle(queries)
queries

array([[ 10366],
       [110318],
       [  2012],
       ..., 
       [ 16337],
       [ 90959],
       [ 20869]])

In [223]:
#Add userId
users = np.random.choice(range(200), 7000, replace=True).reshape(-1,1)

#Add TimeStamp

timestamp = np.array(range(1508513453,1515513453,1000)).reshape(-1,1)

print(queries.shape, users.shape, timestamp.shape)
data = np.concatenate([queries, users, timestamp], axis=1)
#generating data OVER

print(data)

#Select 1/10 using an hash function:
sub_queries = np.array([q for q in data if math.floor(random.random()*10)==1])
print(sub_queries.shape)

(7000, 1) (7000, 1) (7000, 1)
[[     10366        119 1508513453]
 [    110318        126 1508514453]
 [      2012         53 1508515453]
 ..., 
 [     16337        174 1515510453]
 [     90959        189 1515511453]
 [     20869         35 1515512453]]
(679, 3)


With this technique do we have 1/10 of the data for sure? No, we have a noisy approximation of that quantity.

In [242]:
sub_queries.sort()
X = np.diff(sub_queries[:,0])

S = np.append((X==0), False)
S


print("sample percentage")
print(sub_queries.shape[1]/queries.shape[0]*100, "%")
print("-----")
print("Percentage of duplicates (should be 16%)")
#print(sub_queries[S.tolist(),0].shape[0]/sub_queries.shape[0])
print(sub_queries[S.tolist()].shape[0]/sub_queries.shape[0]*100, "%")

sample percentage
0.04285714285714286 %
-----
Percentage of duplicates (should be 16%)
0.14727540500736377 %


Aprox. 10 times less.... why? Because we loose the duplicated proportion information. For aleatory values it can be shown that 

$$ Duplicates = d/(10s+19d)$$

for 0.1 times sample. In this case, 1000/(60000+19000) = 1,2% (aprox 10% of the real value 16%) 

#### Conclusion:

For many statistical queries, sampling destroys data is not well thought. In this case, we should consider other kind of information: for instance, the user: It's preferable to keep a complete query history of less users to have a good estimate of duplicated queries.

**In that case, the hashing function should be done over the userID instead of the queryID**


This allows to have related queries in the sample, and avoid relevant missing duplicates

### 2) Filtering a Data Stream based on a given Set

#### Section 1) made us have a second problem: Filtering a data stream based on a given Set of keys.

If the selection criterion is a property of the regiter that can be calculated (e.g., an attribute is less than 10), then the selection is easy to do. 

**The problem becomes harder when the criterion involves lookup for membership in a set (specially when it does not fit in main memory).**


----

#### Example: Email Filtering based on "from" field using ***one gigabyte memory***:

We have a list of 1E9 email names that are acceptable (if the email has 20 bytes, 20TB of space are needed).

Disk Access? or ...(first Attempt) apply an hash function in this way:


> - Given a set of keys **S** **(valid emails)** that we want to filter
> - Create a bit array **B** of **n bits** (1GB means 8E9 bits), initially all 0s
> - Choose a hash function h with range **[0,n)**
> - Hash each member of s ∈ S to one of n buckets, and set that bit to 1, i.e., B[h(s)]=1   

You have now the filter Ready. Let's Start Sending emails to the filter:

> - For each new email **a** in the stream, Hash it as h(a)
> - **Output a if B[h(a)] == 1**

#### Let's Analyze sizes:

- Number of known emails:

> |S| = 1E9 emails

- Number of bits in the filter:

> |B| = 8 Gbits (Feasible)

- Number of bits setted to 1 in the filter:

> (1/8 of the bits are set to 1 if each email assigns a bit to one - actually the value is slightly less)

- If the email address is in S, then it surely hashes to a bucket set to 1, so it always gets through **(no false negatives)**


- If stream emails are equally spanned by all buckets using $h(a)$, about 1/8th of the addresses not in S get through to the output generating **false positives** (span emails that pass through)




However, there are a better implementation for big data: Bloom Filter (Next Time).

# Graph Based Algorithms

## 1) Page Rank

#### Basic Idea: Links as votes for Ranking pages

Each link’s vote is proportional to the importance of its source page

- If page $j$ with importance $r_j$ has $n$ out-links, each link gets $r_j / n_j$ votes
- Page $j$’s own importance is the sum of the votes on its in-links (I) (A page is important if it is pointed to by other important pages)

So, for a single page $j$, its importance $r_j$ is given by:

$$r_j = \sum_{i=1}^{I} \frac{r_i}{n_i}$$

---

Take a first set of 3 nodes:

<img src="images/page_rank.png" style="width:30%"/>





## Let's write the equations, starting in $y$:

$$r_y =r_y/2+r_a/2 $$

$$r_a =r_y/2+r_m$$ 

$$r_m =r_a /2$$

Is this solvable? What is wrong? The underlying matrix is $Singular$. 
We need a fourth equation to give this a solution:

$$r_m + r_a + r_y = 1$$
---


Let's build a matrix M where this equations are represented in the following order (both rows and columns) $[y, a, m]$
Our system (Homogenous) is then 


$$ 
\begin{bmatrix} 
1/2 & -1/2 & 0\\
-1/2 & 1 & -1\\
0 & -1/2 & 1\\
\end{bmatrix}
\quad
\begin{bmatrix} 
y\\
a\\
m\\
\end{bmatrix} = 
\begin{bmatrix} 
0\\
0\\
0\\
\end{bmatrix}$$

In [244]:
import numpy as np

M = np.array([[0.5, -0.5, 0],
[-0.5, 1, -1],
[0, -0.5, 1]])
print(M)

np.linalg.det(M)

[[ 0.5 -0.5  0. ]
 [-0.5  1.  -1. ]
 [ 0.  -0.5  1. ]]


0.0

We have to add an extra relation between parameters: for instance, a normalization information their relative values like $ y+a+m = 1$, which means a = 1-y-m. Let's use this in the last equation, obtaining $(y+m-1)/2 + m = 0 <=> y/2 + 3/2m  = 1/2$.



$$ 
\begin{bmatrix} 
1/2 & -1/2 & 0\\
-1/2 & 1 & -1\\
1/2 & 0 & 3/2\\
\end{bmatrix}
\quad
\begin{bmatrix} 
y\\
a\\
m\\
\end{bmatrix} = 
\begin{bmatrix} 
0\\
0\\
1/2\\
\end{bmatrix}$$

In [245]:
M = np.array([[0.5, -0.5, 0],
[-0.5, 1, -1],
[1/2, 0, 3/2]])

#np.linalg.inv(M)
b= np.array([[0], [0], [1/2]])

X = np.linalg.solve(M,b)
X

array([[ 0.4],
       [ 0.4],
       [ 0.2]])

But now if M is huge?
linalg uses gaussian elimination. this is not good for huge matrices (Big Data).

Inverting huge matrices is a very relvant subject in general. Also here.